// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Admin: typeof import("./components/admin/admin.vue")["default"];
    Announcements: typeof import("./components/home/Announcements.vue")["default"];
    Courses: typeof import("./components/courses/courses.vue")["default"];
    Editor: typeof import("./components/editor/Editor.vue")["default"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    Footer: typeof import("./components/home/footer.vue")["default"];
    Home: typeof import("./components/home/home.vue")["default"];
    Info: typeof import("./components/info/Info.vue")["default"];
    Main: typeof import("./components/home/main.vue")["default"];
    Menu: typeof import("./components/home/Menu.vue")["default"];
    MessageBox: typeof import("./components/home/MessageBox.vue")["default"];
    Nav: typeof import("./components/home/nav.vue")["default"];
    RegisterLogin: typeof import("./components/register-login/RegisterLogin.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Search: typeof import("./components/home/Search.vue")["default"];
    Swiper: typeof import("./components/home/Swiper.vue")["default"];
    Upload: typeof import("./components/upload/upload.vue")["default"];
  }
}
